config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :responses

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/response.rb
class Response < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new; end

  def create
    p params
    Response.create
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/responses/new.html.erb
<h1>How are you feeling today?</h1>

<%= form_with scope: :responses, url: responses_path, local: true do |form| %>
<p>
<%=form.label :"If you had to describe your day as weather report
what would it be like?" %><br>
</p>

<p>
    <%= form.text_area :weather_report %>
  </p>

  <p>
  <%=form.label :"What was the best thing that happened to you today?" %><br>
  </p>

  <p>
      <%= form.text_area :best_thing_today %>
    </p>

    <p>
    <%=form.label :"How did it make you feel?" %><br>
    </p>

    <p>
        <%= form.text_area :feels %>
      </p>

      <p>
      <%=form.label :"Did you have any low points today?(if yes
      please answer the next question)" %><br>
      </p>

      <p>
          <%= form.text_area :any_low_points %>
        </p>

        <p>
        <%=form.label :"What happened?" %><br>
        </p>

        <p>
            <%= form.text_area :what_happened %>
          </p>

          <p>
          <%=form.label :"How are you feeling right now?" %><br>
          </p>

          <p>
              <%= form.text_area :feels_right_now %>
            </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to My Mind Map</h1>
<br>
<p>
According to mental health charity, Mind, 1 in 6 people in England
reported experiencing a common health problem (such as anxiety or depression).
<br>
All these statistics can sometimes overwhelm us and make us think
that mental health illnesses are on the rise.<br>
In 2016, a digital NHS survey looked into mental health and wellbeing in England,
and found that the overall number of people with mental health problems
had not changed significantly in recent years.<br>
However, the survey showed that the way that we cope with mental health problems
is becoming increasingly difficult and that medication is the most
common type of treatment for a mental health problem.<br>

<h2>About Mind Map</h2>
Mind Map is a test project which is looking to collect data from users
who fill out our form and submit their answers to us about their mental health
in general.
  <br>
It's estimated that 1 in 4 people in the UK will experience a mental health illness
at some point in their life.<br>
But when it comes to ethnic minorities, people from low income groups
and other marginalised communities, the numbers don't match the stories
that people from these communities talk about.<br>

</p>